### PR TITLE
Fix README example

### LINKED ISSUE #47: ERROR: MethodError: no method matching JLSOFile(::Dict{String,Any})
In a clean environment I get an error from the example code in the README:
```julia
julia> JLSO.save("breakfast.jlso", "food" => "☕️🥓🍳", "cost" => 11.95, "time" => Time(9, 0))
ERROR: MethodError: no method matching JLSOFile(::Dict{String,Any})
Closest candidates are:
  JLSOFile(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /home/yakir/.julia/packages/JLSO/MyEw2/src/JLSOFile.jl:2
  JLSOFile(; version, julia, format, compression, image, kwargs...) at /home/yakir/.julia/packages/JLSO/MyEw2/src/JLSOFile.jl:76
  JLSOFile(::VersionNumber, ::VersionNumber, ::Symbol, ::Symbol, ::String, ::Dict{String,Any}, ::Dict{String,Any}, ::Dict{Symbol,Array{UInt8,1}}) at /home/yakir/.julia/packages/JLSO/MyEw2/src/JLSOFile.jl:2
  ...
Stacktrace:
 [1] #save#24(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(JLSO.save), ::IOStream, ::Dict{String,Any}) at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:74
 [2] save(::IOStream, ::Dict{String,Any}) at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:74
 [3] #save#25(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(JLSO.save), ::IOStream, ::Pair{String,String}, ::Vararg{Pair,N} where N) at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:75
 [4] save at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:75 [inlined]
 [5] #27 at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:76 [inlined]
 [6] #open#271(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(open), ::JLSO.var"#27#28"{Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Tuple{Pair{String,String},Pair{String,Float64},Pair{String,Time}}}, ::String, ::Vararg{String,N} where N) at ./io.jl:298
 [7] open(::Function, ::String, ::String) at ./io.jl:296
 [8] #save#26(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(JLSO.save), ::String, ::Pair{String,String}, ::Vararg{Any,N} where N) at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:76
 [9] save(::String, ::Pair{String,String}, ::Pair{String,Float64}, ::Vararg{Any,N} where N) at /home/yakir/.julia/packages/JLSO/MyEw2/src/file_io.jl:76
 [10] top-level scope at REPL[4]:1
```
I'm on:
```julia
(tmp) pkg> st
    Status `~/tmp/Project.toml`
  [9da8a3cd] JLSO v2.0.0
```
and:
```
Julia Version 1.3.1
Commit 2d5741174c* (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen Threadripper 2950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)
```

### PR DESCRIPTION
**Pull request by nickrobinson251**
- closes #47

### CODE REVIEW

File: test/file_io.jl [hunk 1]
```diff
@@ -152,4 +152,27 @@ end
...
+        @test_throws(
+            getlogger(JLSO),
+            MethodError,
+            JLSO.save("breakfast.jlso", "food" => "☕️🥓🍳", "time" => Time(9, 0)),
+        )
+    end
+    @testset "README example" begin
+        mktempdir() do path
+            JLSO.save(
+                "$path/breakfast.jlso",
```
Comment (oxinabox) [inline test/file_io.jl]:
```suggestion
                joinpath(path, "breakfast.jlso"),
```

Comment (nickrobinson251) [reply test/file_io.jl]: thanks :) if using FilePaths, would be even nicer: `path / "breakfast.jlso"`
